import { Content } from './types';

export interface FeedItem extends Content {
  author_name?: string;
  likes_count?: number;
  comments_count?: number;
  is_placeholder?: boolean;
}

/**
 * Placeholder posts for testing feed layout and algorithm.
 * Mix of content types: artwork, poems, apps, games, ideas.
 */
export const PLACEHOLDER_FEED: FeedItem[] = [
  {
    id: 'placeholder-art-1',
    type: 'artwork',
    title: 'Nordlys over Lofoten',
    description: 'Digitalt kunstverk inspirert av nordlys i midnattssol.',
    author_id: null,
    app_id: null,
    url: null,
    image_url: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&h=600&fit=crop',
    body_text: null,
    metadata: {},
    category: 'Kunst',
    tags: ['nordlys', 'lofoten', 'natur'],
    region: null,
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    updated_at: new Date().toISOString(),
    status: 'approved',
    curator_notes: null,
    is_curator_pick: true,
    author_name: 'Kari M.',
    likes_count: 124,
    comments_count: 18,
    is_placeholder: true,
  },
  {
    id: 'placeholder-poem-1',
    type: 'poem',
    title: 'Havet og jeg',
    description: null,
    author_id: null,
    app_id: null,
    url: null,
    image_url: null,
    body_text: 'Havet synger\nog jeg lytter.\nBølgene går\nmens jeg sitter.\n\nAlt forsvinner\ninnen horisont.\nKun vinden\nsom min venn.',
    metadata: {},
    category: null,
    tags: ['poesi', 'natur'],
    region: null,
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updated_at: new Date().toISOString(),
    status: 'approved',
    curator_notes: null,
    is_curator_pick: true,
    author_name: 'Ola N.',
    likes_count: 89,
    comments_count: 12,
    is_placeholder: true,
  },
  {
    id: 'placeholder-app-1',
    type: 'app',
    title: 'Dagsrytme',
    description: 'En enkel app for å spore søvn og sikre god dagsrytme. Inkluderer alarm og statistikk.',
    author_id: null,
    app_id: null,
    url: 'https://example.com',
    image_url: null,
    body_text: null,
    metadata: {},
    category: 'Helse',
    tags: ['søvn', 'helse'],
    region: null,
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updated_at: new Date().toISOString(),
    status: 'approved',
    curator_notes: null,
    is_curator_pick: false,
    author_name: 'Emma S.',
    likes_count: 234,
    comments_count: 31,
    is_placeholder: true,
  },
  {
    id: 'placeholder-art-2',
    type: 'artwork',
    title: 'Abstrakt Oslo',
    description: 'Geometrisk tolkning av Oslo sentrum i solnedgang.',
    author_id: null,
    app_id: null,
    url: null,
    image_url: null,
    body_text: null,
    metadata: {},
    category: 'Kunst',
    tags: ['abstrakt', 'oslo', 'by'],
    region: null,
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    updated_at: new Date().toISOString(),
    status: 'approved',
    curator_notes: null,
    is_curator_pick: false,
    author_name: 'Jonas H.',
    likes_count: 67,
    comments_count: 8,
    is_placeholder: true,
  },
  {
    id: 'placeholder-game-1',
    type: 'game',
    title: 'Trolltur',
    description: 'Et hyggelig plattformspill med norske troll. Perfekt for barn og familien.',
    author_id: null,
    app_id: null,
    url: 'https://example.com',
    image_url: null,
    body_text: null,
    metadata: {},
    category: 'Spill',
    tags: ['plattform', 'familie', 'troll'],
    region: null,
    created_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    updated_at: new Date().toISOString(),
    status: 'approved',
    curator_notes: null,
    is_curator_pick: true,
    author_name: 'Lise K.',
    likes_count: 412,
    comments_count: 56,
    is_placeholder: true,
  },
  {
    id: 'placeholder-idea-1',
    type: 'idea',
    title: 'Felleshage i nabolaget',
    description: 'Hvorfor ikke starte en felleshage der naboene kan dyrke grønnsaker sammen? Her er min plan for hvordan vi kan få det til.',
    author_id: null,
    app_id: null,
    url: null,
    image_url: null,
    body_text: 'Ide: Samle naboer og be kommunen om et lite areal. Fordel bedder, planlegg sesonger, og del høsten. Sosialt og bærekraftig!',
    metadata: {},
    category: 'Bærekraft',
    tags: ['hage', 'nabolag', 'bærekraft'],
    region: null,
    created_at: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    updated_at: new Date().toISOString(),
    status: 'approved',
    curator_notes: null,
    is_curator_pick: false,
    author_name: 'Per A.',
    likes_count: 156,
    comments_count: 24,
    is_placeholder: true,
  },
  {
    id: 'placeholder-poem-2',
    type: 'poem',
    title: 'Første snø',
    description: null,
    author_id: null,
    app_id: null,
    url: null,
    image_url: null,
    body_text: 'Den første flaken\nberører kinnet.\nVerden blir hvit\nog hjertet løfter seg.\n\nEn ny begynnelse\ni hver vinter.',
    metadata: {},
    category: null,
    tags: ['vinter', 'poesi'],
    region: null,
    created_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    updated_at: new Date().toISOString(),
    status: 'approved',
    curator_notes: null,
    is_curator_pick: false,
    author_name: 'Anna L.',
    likes_count: 203,
    comments_count: 19,
    is_placeholder: true,
  },
  {
    id: 'placeholder-art-3',
    type: 'artwork',
    title: 'Bergen i regn',
    description: 'Akvarell av bryggen i typisk bergensvær.',
    author_id: null,
    app_id: null,
    url: null,
    image_url: null,
    body_text: null,
    metadata: {},
    category: 'Kunst',
    tags: ['bergen', 'akvarell', 'natur'],
    region: null,
    created_at: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    updated_at: new Date().toISOString(),
    status: 'approved',
    curator_notes: null,
    is_curator_pick: false,
    author_name: 'Sigrid B.',
    likes_count: 98,
    comments_count: 11,
    is_placeholder: true,
  },
  {
    id: 'placeholder-article-1',
    type: 'article',
    title: 'Slik bygger vi trygg digital frivillighet',
    description: 'En kort artikkel om inkluderende teknologi, lokalt engasjement og personvern i praksis.',
    author_id: null,
    app_id: null,
    url: null,
    image_url: null,
    body_text:
      'Når lokalsamfunn bruker digitale verktøy på en klok måte, kan flere delta i aktiviteter og dugnader. Nøkkelen er enkel onboarding, tydelig ansvar og gode personvernvalg.',
    metadata: { reading_time_min: 4 },
    category: 'Samfunn',
    tags: ['artikkel', 'frivillighet', 'personvern'],
    region: 'Oslo',
    created_at: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
    updated_at: new Date().toISOString(),
    status: 'approved',
    curator_notes: null,
    is_curator_pick: false,
    author_name: 'Nytti redaksjon',
    likes_count: 74,
    comments_count: 9,
    is_placeholder: true,
  },
  {
    id: 'placeholder-dugnad-1',
    type: 'dugnad',
    title: 'Felles strandrydding på Bygdøy',
    description: 'Bli med å rydde plast og avfall langs stranden. Utstyr deles ut ved oppmøte.',
    author_id: null,
    app_id: null,
    url: null,
    image_url: null,
    body_text: 'Oppmøte ved parkeringsplassen kl. 17:00. Ta med gode sko og hansker hvis du har.',
    metadata: { organizer: 'Bygdøy Frivilligsentral' },
    category: 'Miljø',
    tags: ['dugnad', 'strandrydding', 'oslo'],
    region: 'Oslo',
    latitude: 59.9042,
    longitude: 10.6843,
    address: 'Bygdøy sjøbad, Oslo',
    location_name: 'Bygdøy',
    starts_at: new Date(Date.now() + 1000 * 60 * 60 * 26).toISOString(),
    ends_at: new Date(Date.now() + 1000 * 60 * 60 * 29).toISOString(),
    capacity: 60,
    organizer: 'Bygdøy Frivilligsentral',
    contact: 'dugnad@bygdoy.no',
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updated_at: new Date().toISOString(),
    status: 'approved',
    curator_notes: null,
    is_curator_pick: true,
    author_name: 'Bygdøy Frivilligsentral',
    likes_count: 142,
    comments_count: 21,
    is_placeholder: true,
  },
  {
    id: 'placeholder-event-1',
    type: 'event',
    title: 'Åpent verksted: Lag din egen app-idé',
    description: 'Gratis kveldssamling for ungdom og voksne med interesse for samfunnsnyttige apper.',
    author_id: null,
    app_id: null,
    url: null,
    image_url: null,
    body_text: 'Praktisk workshop med mentorer, pizza og korte idé-pitcher.',
    metadata: { organizer: 'Nytti Lab' },
    category: 'Teknologi',
    tags: ['event', 'workshop', 'app'],
    region: 'Bergen',
    latitude: 60.3928,
    longitude: 5.3223,
    address: 'Media City Bergen',
    location_name: 'Bergen sentrum',
    starts_at: new Date(Date.now() + 1000 * 60 * 60 * 50).toISOString(),
    ends_at: new Date(Date.now() + 1000 * 60 * 60 * 54).toISOString(),
    capacity: 120,
    organizer: 'Nytti Lab',
    contact: 'lab@nytti.no',
    created_at: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    updated_at: new Date().toISOString(),
    status: 'approved',
    curator_notes: null,
    is_curator_pick: false,
    author_name: 'Nytti Lab',
    likes_count: 68,
    comments_count: 6,
    is_placeholder: true,
  },
];

